---
# tasks file for roles/koji-prerequisite

- name: Install Python, mc, epel and deps for Ansible Modules
  package:
    name:
      - libselinux-python3
      - mc
      - epel-release
    state: present 
